# Generated by Django 4.1.1 on 2022-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metering_code', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('primary_value', models.FloatField()),
                ('type', models.CharField(default='Heat', max_length=255)),
                ('apartment', models.CharField(default='a0A9K00000012qSUAQ', max_length=255)),
            ],
        ),
    ]
